# This is a basic workflow to help you get started with Actions
name: dbt CI/CD

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "default:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: SYSADMIN
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: SILVER
                threads: 6" > ~/.dbt/profiles.yml
