name: dbt CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install DBT and adapter
        run: |
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake

      - name: Install dbt dependencies
        run: dbt deps

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      user: ${{ secrets.SNOWFLAKE_USER }}
      password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      role: ACCOUNTADMIN
      database: ${{ secrets.SNOWFLAKE_DATABASE }}
      warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      schema: RAW
      threads: 6
EOF
